### Bitwise XOR operations

In [3]:
import numpy as np
import h5py

In [4]:
a = [1,1,1,1]
b = [4,1,1,4]
np.bitwise_xor(a,b)

array([5, 0, 0, 5])

In [5]:
# variables for next cell

filepath = '/media/storage/DATA/lfads_export/f1_221027.h5'
with h5py.File(filepath, 'r') as f:

    # get stimulus presentations
    stimuli = f['visuomotor']['presentations']
    stim_type = stimuli['stim_type'].astype(int)

    # find the presentation indexes with left or right spots
    stim_pres_idx_l = np.where(np.isin(stim_type, 1))[0]    # left spots
    stim_pres_idx_r = np.where(np.isin(stim_type, 2))[0]    # right spots

    # index stim onset frames with the presentation indexes
    stim_onset_fr = stimuli['onset_frame'].astype(int)
    stim_pres_fr_l = stim_onset_fr[stim_pres_idx_l]
    stim_pres_fr_r = stim_onset_fr[stim_pres_idx_r]

    # index stim end frames with the presentation indexes
    stim_end_fr = stimuli['offset_frame'].astype(int)
    stim_end_fr_l = stim_end_fr[stim_pres_idx_l]
    stim_end_fr_r = stim_end_fr[stim_pres_idx_r]

In [12]:
a = np.zeros((100000,)).astype(int)
a[[stim_pres_fr_l.astype(int), stim_end_fr_l.astype(int)]] = 1
print(a[793:825])
a = np.bitwise_xor.accumulate(a) | a
a[793:825]


[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [7]:
a = np.array([1,1,1,1])
b = np.array([4,1,1,4])
np.bitwise_xor.accumulate(a)|a

array([1, 1, 1, 1])